version: '3.8'
services:
  app:
    build: ./main
    container_name: app-log
    command: "flask run --host 0.0.0.0"
    ports:
      - "5001:5000"
    volumes:
      - ./main:/app
    depends_on:
      rabbitmq:
        condition: service_started
      db2:
        condition: service_healthy

  db2:
    image: mysql:latest
    container_name: db-logAnalizer
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_DATABASE=logAnalizer
      - MYSQL_USER=analyst
      - MYSQL_PASSWORD=analyst
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./main/.dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql" , "-h", "localhost", "--port=3306", "--protocol=TCP", "-uroot", "-proot"]
      timeout: 60s
      retries: 120
    ports:
      - 3307:3306

  backend:
    build: ./admin
    container_name: microservice
    ports:
      - 8000:8000
    volumes:
      - ./admin:/app
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_healthy
  
  db:
    image: mysql:latest
    container_name: db-microservice
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./admin/.dbdata:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
    healthcheck:
      test: ["CMD", "mysql" , "-h", "localhost", "--port=3306", "--protocol=TCP", "-uroot", "-proot"]
      timeout: 60s
      retries: 120
    ports:
      - 3306:3306
    
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8081:8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/scripts:/scripts
    depends_on:
      - backend
      - app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq/

  # request-analyzer:
  #   build: ./main
  #   command: "python -u request_analyzer.py"
  #   volumes:
  #     - ./main:/app
  #   depends_on:
  #     rabbitmq:
  #       condition: service_started
  #     db2:
  #       condition: service_healthy
  
  request_analyzer:
    build: ./main
    container_name: request_analyzer
    command: "flask --app request_analyzer run --host 0.0.0.0"
    ports:
      - "5002:5000"
    volumes:
      - ./main:/app
    depends_on:
      rabbitmq:
        condition: service_started
      db2:
        condition: service_healthy

  reputation_control:
    build: ./main
    container_name: reputation_control
    command: "flask --app reputation_control run --host 0.0.0.0"
    ports:
      - "5003:5000"
    volumes:
      - ./main:/app
    depends_on:
      rabbitmq:
        condition: service_started
      db2:
        condition: service_healthy