version: '3'
services:
  main:
    build: .
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      db2:
        condition: service_healthy
  
  db2:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=loren
      - MYSQL_PASSWORD=loren
      - MYSQL_ROOT_PASSWORD=loren
    volumes:
      - .dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql" , "-h", "localhost", "--port=3306", "--protocol=TCP", "-uloren", "-ploren"]
      timeout: 60s
      retries: 120
    ports:
      - 3307:3306